GET http://localhost:3000/user
###
GET http://localhost:3000/user/11
###
POST http://localhost:3000/user
Content-Type: application/json

{
	"id":11,
	"user": "john",
	"pass":"ripper"
}

###
PUT http://localhost:3000/user
Content-Type: application/json

{
	"id":1,
	"user": "john",
	"pass":"ripper"
}

###
DELETE http://localhost:3000/user
Content-Type: application/json

{
	"id":11
}
